travis:
  secure:
    BINSTAR_TOKEN: cxt8Ke1/9a1Z/tHu7/SPFkSfZkqfeEPmWmtGSwq7e5eSh7N7RMTYxALmCyW/DB2b4MXETXLI6LoS0drywVzC213agTCYQMyElk86HHBzwtiPASeFgCItePDeOhxYaxrEfr4G4U7WpuouLWsu2J6tlBCnjQwesXbUYnnEnDUjI0/5NyVyykxnAWc+o+an5OXPaOtUVSkT7aYC60Brz1YFUDjOexxIvAHVF+8D7BgesOVIRf3WgW75UllkNR+q7emsfxyXG6aMPHNTZG7YWJWuZhyTBnXY2V14zokkEfxiFajKlY4dzXdxqP2hpIpW1THgD6zdMoehxfW7RTek/V5cbIP39PcUvlolzFPMsOtPmUxJVmK5pm6HIN/7lzoL3JUDi1jKKXnpjd1qQpKE+ZtTgo495HJrsJCdPHd9ZwdGSBEAYXQrsv0vQPktWhXxD64wKY/tDbQ3Y1g84CMjD6X/+RstDrtFaQY5oZa0UG1WbVuNnmA5rFknejTaAEUoGAThLlHDtxIFIKNvMlCdmBSWP8Xrwb4CVLdSlyk0XchbhOfY7deV8JS8GnMaKfagcIUIJ2StzenQ4kNEsjBGnOyfJS/7vbwPoJnlQGpAh33rryM87FLwhMNs9cBWyscadWle8cpGWuWslqIDKm8nJWZCssHgx8hVeMlRzFaCPsubm38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
